export const productDB = [
  {
    id: 1,
    title: " xbox series s",
    price: "100",
    oldprice: "200",
    brand: "xbox",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "console",
  },
  {
    id: 2,
    title: "iphone xr",
    price: "150",
    oldprice: "300",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "iphone",
  },
  {
    id: 3,
    title: "samsung s10",
    price: "530",
    oldprice: "1,000",
    brand: "samsung",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "",
  },
  {
    id: 4,
    title: "iphone 11",
    price: "210",
    oldprice: "400",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "iphone",
  },
  {
    id: 5,
    title: "iphone 11 pro max",
    price: "340",
    oldprice: "600",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "iphone",
  },
  {
    id: 6,
    title: "iphone 13",
    price: "300",
    oldprice: "600",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "iphone",
  },
  {
    id: 7,
    title: "imac",
    price: "510",
    oldprice: "1,000",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "macbook",
  },
  {
    id: 8,
    title: "samsung s21",
    price: "150",
    oldprice: "300",
    brand: "samsung",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "andriod",
  },
  {
    id: 9,
    title: "samsung s21 ultra",
    price: "250",
    oldprice: "500",
    brand: "samsung",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "andriod",
  },
  //  {id:, title:,price:,oldprice:,brand:,description:, image:, incart:true, rating: { rate: "4.1/5", view: 54 }, type: "",},
  {
    id: 10,
    title: "samsung s22 ultra",
    price: "348",
    oldprice: "600",
    brand: "samsung",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "andriod",
  },
  {
    id: 11,
    title: "playstation 4",
    price: "300",
    oldprice: "600",
    brand: "sony",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "console",
  },
  {
    id: 12,
    title: "samsung s23 ultra",
    price: "450",
    oldprice: "900",
    brand: "samsung",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "andriod",
  },
  {
    id: 13,
    title: "samsung s24 ultra",
    price: "1,000",
    oldprice: "2,000",
    brand: "samsung",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "andriod",
  },
  {
    id: 14,
    title: "playstation 5",
    price: "320",
    oldprice: "640",
    brand: "sony",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "console",
  },
  {
    id: 15,
    title: "macbook air",
    price: "470",
    oldprice: "1,000",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "macbook",
  },
  {
    id: 16,
    title: "macbook pro",
    price: "680",
    oldprice: "1,200",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "macbook",
  },
  {
    id: 17,
    title: "dell xps",
    price: "230",
    oldprice: "700",
    brand: "windows",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "windows",
  },
  {
    id: 18,
    title: "hp elitebook",
    price: "230",
    oldprice: "300",
    brand: "windows",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "windows",
  },
  {
    id: 19,
    title: "ipad air",
    price: "650",
    oldprice: "1,450",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "tablet",
  },
  {
    id: 20,
    title: "ipad pro",
    price: "750",
    oldprice: "1,200",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "tablet",
  },
  {
    id: 21,
    title: "ipad mini",
    price: "320.43",
    oldprice: "536.99",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "tablet",
  },
  {
    id: 22,
    title: "airpods pro 2",
    price: "430.23",
    oldprice: "880.99",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "airpods",
  },
  {
    id: 23,
    title: "airpods 2",
    price: "179.99",
    oldprice: "309.99",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "airpods",
  },
  {
    id: 24,
    title: "airpods 3",
    price: "219.78",
    oldprice: "449.99",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "airpods",
  },
  {
    id: 25,
    title: "airpods pro 3",
    price: "456.99",
    oldprice: "901.99",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "airpods",
  },
  {
    id: 26,
    title: "airpods max",
    price: "509.89",
    oldprice: "1,199.99",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "airpods",
  },
  {
    id: 27,
    title: "apple watch",
    price: "129.99",
    oldprice: "239.99",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "watch",
  },
  {
    id: 28,
    title: "apple watch ultra",
    price: "220.54",
    oldprice: "570.99",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "watch",
  },
  {
    id: 29,
    title: "samsung s23",
    price: "307.39",
    oldprice: "600.99",
    brand: "samsung",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "andriod",
  },
  {
    id: 30,
    title: "iphone x",
    price: "154.99",
    oldprice: "399.99",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "iphone",
  },
  {
    id: 31,
    title: "iphone 13 pro max ",
    price: "504.99",
    oldprice: "1,199.99",
    brand: "apple",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "iphone",
  },
  {
    id: 32,
    title: "ROG zeperus 14",
    price: "1,250.78",
    oldprice: "1,599.99",
    brand: "asus",
    description: "",
    image: "",
    incart: true,
    rating: { rate: "4.1/5", view: 54 },
    type: "windows",
  },
];
